### PR TITLE
Keybind improvements

### PR DESCRIPTION
**Pull request by samingle**
• Added a global keybind service so individual views can register keypresses
• Changed debug component to `log` so it'll auto scroll as new data comes in
• Worked around react-blessed bug so `log` scrolling actually works
• Moved `list` component to top level of block-details
• Worked around react-blessed bug so `list` scrolling actually works
• Reworked selection logic on block details so it's based on block height rather than index. keep your selection as new data comes in.
• Reworked types for block data to clean up data & fix duplicates

### CODE REVIEW

**Comment by samingle** [comment]
based on code from #9

**Comment by mikedotexe** [comment]
I'm getting:

Screen Shot 2022-08-08 at 5 55 55 PM

**Comment by mikedotexe** [comment]
Looking good. The **Transaction Details** pane looks like it's less pretty and structured compared to `main`.

On this branch, I'm seeing this:

Screen Shot 2022-08-08 at 6 04 46 PM

Note the highlighted sections showing unstructured stuff, which is how it's saved, but not that great for developers, who are the target users for this. And then under `tx` it's a bunch of bytes.

------

On the `main` branch when I run the same Bank Message I get…

A pretty raw log:

Screen Shot 2022-08-08 at 6 05 59 PM

A readable `tx` (shorthand for transaction in snooty blockchain lingo) which decodes most stuff, unless it's totally useless, in which case I was like, "eh, let's just base64 encode it so it's not just bytes" (I think I did this for a Signature if I recall)

Screen Shot 2022-08-08 at 6 06 23 PM

So I think it would be great to get the prettiest form back before merging, but open to having that be another ticket, too.

**Review by mikedotexe — APPROVED** [review]
lfgtm

**Pull request merged**
